version: '3'

services:
  service.rss2:
    build: .
    container_name: rss2
    ports:
      - 8090:8090
    links:
      - rss2_redis
  rss2_redis:
    image: redis:alpine
    container_name: rss2_redis
    volumes:
      - ~/docker/rss2/redis/:/redis/data
    restart: always
