version: '3'

services:
  rss2:
    image: registry.cn-hangzhou.aliyuncs.com/91go/rss2:latest
    container_name: rss2-service
    ports:
      - 8090:8090
    links:
      - redis
    depends_on:
      - redis
    networks:
      - rss2
    environment:
      - TZ=Asia/Shanghai

  redis:
    image: redis:alpine
    container_name: rss2-redis
    volumes:
      - ~/docker/rss2/redis/:/redis/data
    restart: always
    networks:
      - rss2

networks:
  rss2:
    driver: bridge