version: '3'

services:
  rss2:
    image: registry.cn-hangzhou.aliyuncs.com/91go/rss2:latest
    container_name: rss2-service
    ports:
      - 8090:8090
    links:
      - redis
    depends_on:
      - redis
    networks:
      - rss2
    environment:
      - TZ=Asia/Shanghai
      - DINGTALK.TOKEN=38eeb8495dff05be270f3737ba48d3b7efa7215b548e380920b9f00352102596
      - DINGTALK.SECRET=SECa32bcc1ab984fd188e7b7718c2aa9da980b3b2261ac251c713d0ce78e1ff830a
      - REDIS.ADDR=rss2-redis:6379
      - REDIS.PWD=root
      - REDIS.DB=1

  redis:
    image: redis:alpine
    container_name: rss2-redis
    volumes:
      - ~/docker/rss2/redis/:/redis/data
    restart: always
    networks:
      - rss2

networks:
  rss2:
    driver: bridge