version: '3'

services:
  service.rss2:
    build: .
    container_name: rss2
    ports:
      - 8090:8090
    links:
      - rss2_redis
    depends_on:
      - rss2_redis
    networks:
      - rss2

  rss2_redis:
    image: redis:6.0.10-alpine3.12
    container_name: rss2_redis
    volumes:
      - ~/docker/rss2/redis/:/redis/data
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass root --appendonly yes
    networks:
      - rss2

networks:
  rss2:
    driver: bridge