name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    if: github.repository == '91go/rss2'
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Draft
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}