name: test && deploy
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run Unit tests.
        run: go test ./...

#      - name: Upload Coverage report to CodeCov
#        uses: codecov/codecov-action@v1.0.0
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: ./coverage.txt

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SERVER_SSH_PWD }}
          port: 22
          timeout: 10m
          script_stop: true
          script: |
            whoami
            cd ~/data/rss2 && git pull && docker-compose prune && docker-compose up -d





#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    needs: [ lint, test ]
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.17.x
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Build
#        run: go build